/*
 * Copyright (c) 2026 @Natfii. All rights reserved.
 */

package com.zeroclaw.android.data.saf

import android.content.Context
import android.net.Uri
import com.zeroclaw.ffi.FfiException
import com.zeroclaw.ffi.SharedFolderHandler
import java.io.File
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

private const val DEFAULT_WORKFLOW_FOLDER_NAME = "workflow"

/**
 * UniFFI callback handler that bridges Rust tool dispatch to SAF operations.
 *
 * Implements the [SharedFolderHandler] callback interface generated by UniFFI.
 * Parses tool parameters from JSON, delegates to [SharedFolderSafHelper],
 * and returns JSON result strings.
 *
 * @param context Android context for SAF access.
 * @param getFolderUri Lambda returning the current persisted SAF URI string.
 * @param getWorkflowFolderUri Lambda returning the optional persisted workflow SAF URI.
 * @param workflowFolderRoot Lambda returning the app-owned default workflow folder.
 */
class SharedFolderCallbackHandler(
    private val context: Context,
    private val getFolderUri: () -> String,
    private val getWorkflowFolderUri: () -> String = { "" },
    private val workflowFolderRoot: () -> File = { File(context.filesDir, DEFAULT_WORKFLOW_FOLDER_NAME) },
) : SharedFolderHandler {
    private val helper = SharedFolderSafHelper(context)
    private val workflowFileHelper = WorkflowFolderFileHelper()
    private val json = Json { ignoreUnknownKeys = true }

    override fun executeSharedFolderTool(
        toolName: String,
        paramsJson: String,
    ): String {
        return when {
            toolName.startsWith("shared_folder_") ->
                executeSafTool(
                    toolName = toolName,
                    paramsJson = paramsJson,
                    uriString = getFolderUri(),
                    missingFolderMessage =
                        "No shared folder configured. Pick a folder in Hub > Plugins > Shared Folder.",
                )
            toolName.startsWith("workflow_folder_") -> executeWorkflowTool(toolName, paramsJson)
            else -> throw FfiException.InvalidArgument("Unknown tool: $toolName")
        }
    }

    private fun executeSafTool(
        toolName: String,
        paramsJson: String,
        uriString: String,
        missingFolderMessage: String,
    ): String {
        if (uriString.isBlank()) {
            throw FfiException.StateException(missingFolderMessage)
        }
        val rootUri = Uri.parse(uriString)

        return when (toolName) {
            "shared_folder_list" -> {
                val params = json.decodeFromString<ListParams>(paramsJson)
                helper.list(rootUri, params.path)
            }
            "shared_folder_read" -> {
                val params = json.decodeFromString<ReadParams>(paramsJson)
                helper.read(rootUri, params.path)
            }
            "shared_folder_write" -> {
                val params = json.decodeFromString<WriteParams>(paramsJson)
                helper.write(rootUri, params.path, params.content, params.isBase64, params.mkdir)
            }
            "workflow_folder_list" -> {
                val params = json.decodeFromString<ListParams>(paramsJson)
                helper.list(rootUri, params.path)
            }
            "workflow_folder_read" -> {
                val params = json.decodeFromString<ReadParams>(paramsJson)
                helper.read(rootUri, params.path)
            }
            "workflow_folder_write" -> {
                val params = json.decodeFromString<WriteParams>(paramsJson)
                helper.write(rootUri, params.path, params.content, params.isBase64, params.mkdir)
            }
            else -> throw FfiException.InvalidArgument("Unknown tool: $toolName")
        }
    }

    private fun executeWorkflowTool(
        toolName: String,
        paramsJson: String,
    ): String {
        val workflowUri = getWorkflowFolderUri()
        if (workflowUri.isNotBlank()) {
            return executeSafTool(
                toolName = toolName,
                paramsJson = paramsJson,
                uriString = workflowUri,
                missingFolderMessage =
                    "No workflow folder configured. Pick a folder in Hub > Plugins > Workflow Folder.",
            )
        }

        val root = workflowFolderRoot()
        return when (toolName) {
            "workflow_folder_list" -> {
                val params = json.decodeFromString<ListParams>(paramsJson)
                workflowFileHelper.list(root, params.path)
            }
            "workflow_folder_read" -> {
                val params = json.decodeFromString<ReadParams>(paramsJson)
                workflowFileHelper.read(root, params.path)
            }
            "workflow_folder_write" -> {
                val params = json.decodeFromString<WriteParams>(paramsJson)
                workflowFileHelper.write(root, params.path, params.content, params.isBase64, params.mkdir)
            }
            else -> throw FfiException.InvalidArgument("Unknown tool: $toolName")
        }
    }

    @Serializable
    private data class ListParams(
        val path: String = "/",
    )

    @Serializable
    private data class ReadParams(
        val path: String,
    )

    @Serializable
    private data class WriteParams(
        val path: String,
        val content: String? = null,
        @SerialName("is_base64")
        val isBase64: Boolean = false,
        val mkdir: Boolean = false,
    )
}
