/*
 * Copyright 2026 Zero-Assist Community
 *
 * MIT License — see LICENSE in the project root.
 */

package com.zeroclaw.android.ui.screen.dashboard

import android.app.Application
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.zeroclaw.android.ZeroClawApplication
import com.zeroclaw.android.data.ProviderRegistry
import java.time.LocalDateTime
import java.time.LocalTime
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject

/**
 * ViewModel responsible for the dashboard's welcome message.
 * Shows a personalized greeting up to 3x per day, generated by the user's
 * configured AI provider with a local deterministic fallback.
 */
class WelcomeViewModel(
    application: Application,
) : AndroidViewModel(application) {
    private val app = application as ZeroClawApplication
    private val settingsRepository = app.settingsRepository
    private val apiKeyRepository = app.apiKeyRepository
    private val agentRepository = app.agentRepository
    private val welcomeRepository = app.welcomeRepository

    private val _shouldShowWelcome = MutableStateFlow(false)
    val shouldShowWelcome: StateFlow<Boolean> = _shouldShowWelcome.asStateFlow()

    private val _greetingText =
        MutableStateFlow(
            buildGreetingText(
                name = FALLBACK_USER_NAME,
                time = LocalTime.now(),
            ),
        )
    val greetingText: StateFlow<String> = _greetingText.asStateFlow()

    init {
        viewModelScope.launch {
            val settings = settingsRepository.settings.first()
            val lastShownDate = welcomeRepository.lastShownDate.first()
            val now = LocalDateTime.now()
            val todayIsoDate = now.toLocalDate().toString()

            val name = extractUserName(settings.identityJson)

            // Try AI greeting if under 3/day limit
            val aiGreeting = tryAiGreeting(name, now, todayIsoDate)

            val greeting = aiGreeting
                ?: buildGreetingText(name = name, time = now.toLocalTime())

            _greetingText.value = greeting

            // Always show the welcome greeting on every app launch.
            // The date check only gates whether we record today's date (for AI call budgeting).
            _shouldShowWelcome.value = true
            if (lastShownDate != todayIsoDate) {
                runCatching {
                    welcomeRepository.setLastShownDate(todayIsoDate)
                }
            }
        }
    }

    private suspend fun tryAiGreeting(
        name: String,
        now: LocalDateTime,
        todayIsoDate: String,
    ): String? {
        if (!welcomeRepository.tryConsumeAiCall(todayIsoDate)) return null

        return withContext(Dispatchers.IO) {
            try {
                val settings = settingsRepository.settings.first()
                val agents = agentRepository.agents.first()
                val primaryAgent = agents.firstOrNull {
                    it.isEnabled && it.provider.isNotBlank() && it.modelName.isNotBlank() && it.provider != "on-device"
                }
                val providerId = primaryAgent?.provider ?: settings.defaultProvider
                if (providerId.isBlank()) return@withContext null

                val apiKey = apiKeyRepository.getByProviderFresh(providerId)
                    ?: return@withContext null

                val providerInfo = ProviderRegistry.findById(providerId)
                    ?: return@withContext null
                val baseUrl = apiKey.baseUrl.ifBlank { providerInfo.defaultBaseUrl }
                val model = primaryAgent?.modelName ?: providerInfo.suggestedModels.firstOrNull()
                    ?: return@withContext null

                val client = WelcomeAiGreetingClient(
                    apiKey = apiKey.key,
                    baseUrl = baseUrl,
                    model = model,
                )
                client.generateGreeting(name = name, hour = now.hour)
            } catch (e: Exception) {
                Log.w(TAG, "AI greeting failed, using fallback: ${e.message}")
                null
            }
        }
    }

    companion object {
        private const val TAG = "WelcomeViewModel"
    }
}

internal data class WelcomeMessageState(
    val shouldShowWelcome: Boolean,
    val greetingText: String,
    val todayIsoDate: String,
)

internal fun resolveWelcomeMessageState(
    identityJson: String,
    lastShownDate: String?,
    now: LocalDateTime,
): WelcomeMessageState {
    val todayIsoDate = now.toLocalDate().toString()
    return WelcomeMessageState(
        shouldShowWelcome = lastShownDate != todayIsoDate,
        greetingText =
            buildGreetingText(
                name = extractUserName(identityJson),
                time = now.toLocalTime(),
            ),
        todayIsoDate = todayIsoDate,
    )
}

internal fun buildGreetingText(
    name: String,
    time: LocalTime,
): String {
    val normalizedName = name.trim().ifBlank { FALLBACK_USER_NAME }
    val (pool, periodIndex) =
        when (time.hour) {
            in MORNING_HOURS -> MORNING_GREETINGS to 0
            in AFTERNOON_HOURS -> AFTERNOON_GREETINGS to 1
            else -> EVENING_GREETINGS to 2
        }
    val index = deterministicIndex(time, periodIndex, pool.size)
    return "${pool[index]}, $normalizedName!"
}

private fun deterministicIndex(time: LocalTime, periodIndex: Int, poolSize: Int): Int {
    val seed = (time.hour * 60 + time.minute) + periodIndex * 1000
    return seed.mod(poolSize)
}

internal fun extractUserName(identityJson: String): String {
    if (identityJson.isBlank()) return FALLBACK_USER_NAME
    return runCatching {
        val root = JSONObject(identityJson)
        val identity = root.optJSONObject("identity") ?: root
        identity.optString("user_name", FALLBACK_USER_NAME).trim().ifBlank { FALLBACK_USER_NAME }
    }.getOrDefault(FALLBACK_USER_NAME)
}

private val MORNING_HOURS = 5..11
private val AFTERNOON_HOURS = 12..17
private const val FALLBACK_USER_NAME = "User"

internal val MORNING_GREETINGS =
    listOf(
        "Good morning",
        "Rise and shine",
        "Morning",
        "Top of the morning",
        "A fresh start awaits",
        "Good to see you",
        "Welcome back",
        "Hey there",
        "Ready to conquer the day",
        "Let's make today count",
        "Another beautiful morning",
        "Time to shine",
        "Hello sunshine",
        "What a great morning",
        "Morning glory",
    )

internal val AFTERNOON_GREETINGS =
    listOf(
        "Good afternoon",
        "Hey there",
        "Afternoon",
        "Good to see you",
        "How's it going",
        "Welcome back",
        "Hey",
        "Nice to see you",
        "Hope your day is going well",
        "Keep up the great work",
        "Afternoon check-in",
        "How's the day treating you",
        "Still going strong",
        "You're doing great",
        "Halfway through, keep it up",
    )

internal val EVENING_GREETINGS =
    listOf(
        "Good evening",
        "Evening",
        "Hey there",
        "Good to see you",
        "Welcome back",
        "Night owl",
        "How was your day",
        "Time to unwind",
        "Hey",
        "Hope you had a great day",
        "Winding down",
        "Evening check-in",
        "Good to see you again",
        "Still at it",
        "What a day",
    )
